In [1]:
# №1 Створіть одновимірний масив (вектор) з найменшими непарними числами, не менше 15, та виведіть його значення
import numpy as np

odd_numbers = np.arange(15, 35, 2) 

print("Одновимірний масив (вектор) з найменшими непарними числами, не менше 15:")
print(odd_numbers)


Одновимірний масив (вектор) з найменшими непарними числами, не менше 15:
[15 17 19 21 23 25 27 29 31 33]


In [6]:
# №2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями випадкових дійсних чисел від 0 до одиниці.
import numpy as np

matrix = np.random.rand(3, 3) 

print("Двовимірний масив (матриця) розміром 3x3 з випадковими дійсними числами від 0 до одиниці:")
print(matrix)

Двовимірний масив (матриця) розміром 3x3 з випадковими дійсними числами від 0 до одиниці:
[[0.20417986 0.68613856 0.63240115]
 [0.61221748 0.00162568 0.54653793]
 [0.42236653 0.46504625 0.70129244]]


In [5]:

# №3 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від 0 до 1 та знайдіть мін. елемент.
import numpy as np

matrix = np.random.rand(3, 3)

min_element = np.min(matrix)

print("Масив розміром 3x3 з випадковими дійсними числами від 0 до 1:")
print(matrix)
print("\nМінімальний елемент у масиві:")
print(min_element)


Масив розміром 3x3 з випадковими дійсними числами від 0 до 1:
[[0.46225295 0.21858569 0.48903573]
 [0.0189369  0.37283687 0.49932629]
 [0.49837484 0.49074874 0.79382572]]

Мінімальний елемент у масиві:
0.018936900042925364


In [7]:
# №4 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить мінімальні елементи в кожному рядку.
import numpy as np

matrix = np.random.rand(3, 3)

min_vector = np.min(matrix, axis=1).reshape(-1, 1)

print("Масив розміром 3x3 з випадковими дійсними числами від 0 до 1:")
print(matrix)
print("\nВектор-стовпчик, що містить мінімальні елементи в кожному рядку:")
print(min_vector)


Масив розміром 3x3 з випадковими дійсними числами від 0 до 1:
[[0.32230931 0.42029372 0.19446596]
 [0.77036135 0.29744235 0.1863069 ]
 [0.50780352 0.57199694 0.55238133]]

Вектор-стовпчик, що містить мінімальні елементи в кожному рядку:
[[0.19446596]
 [0.1863069 ]
 [0.50780352]]


In [10]:
# №5 Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами від -5 до 5 та виконайте на них поелементні операції додавання, віднімання та множення.
import numpy as np

array1 = np.random.randint(-5, 6, 4)
array2 = np.random.randint(-5, 6, 4)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Перший масив:")
print(array1)
print("\nДругий масив:")
print(array2)

print("\nРезультат поелементного додавання:")
print(addition)
print("\nРезультат поелементного віднімання:")
print(subtraction)
print("\nРезультат поелементного множення:")
print(multiplication)


Перший масив:
[-4 -2 -2  5]

Другий масив:
[-1  4 -1 -2]

Результат поелементного додавання:
[-5  2 -3  3]

Результат поелементного віднімання:
[-3 -6 -1  7]

Результат поелементного множення:
[  4  -8   2 -10]


In [11]:
# №6 Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток
import numpy as np

matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))

product = np.dot(matrix1, matrix2)

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nДобуток двох матриць:")
print(product)


Перша матриця:
[[ 6  6  7]
 [ 4  9  5]
 [ 3  4 10]]

Друга матриця:
[[ 6  5 10]
 [ 1  3  1]
 [ 7  9  7]]

Добуток двох матриць:
[[ 91 111 115]
 [ 68  92  84]
 [ 92 117 104]]


In [12]:
# №7 Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.
import numpy as np

matrix1 = np.random.randint(1, 5, (2, 3))

matrix2 = np.random.randint(1, 5, (3, 3))

product = np.dot(matrix1, matrix2)

print("Перша матриця (2x3):")
print(matrix1)
print("\nДруга матриця (3x3):")
print(matrix2)
print("\nДобуток двох матриць (2x3 * 3x3):")
print(product)


Перша матриця (2x3):
[[4 2 3]
 [2 2 3]]

Друга матриця (3x3):
[[4 3 2]
 [1 2 4]
 [1 4 1]]

Добуток двох матриць (2x3 * 3x3):
[[21 28 19]
 [13 22 15]]


In [13]:
# №8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.
import numpy as np

np.random.seed(0)

matrix = np.random.randint(1, 13, size=(3, 3))
print("Оригінальна матриця:")
print(matrix)
if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
else:
    print("Матриця є виродженою і обернену матрицю знайти неможливо.")


Оригінальна матриця:
[[ 6  1  4]
 [12  4  8]
 [10  4  6]]
Обернена матриця:
[[ 1.   -1.25  1.  ]
 [-1.    0.5  -0.  ]
 [-1.    1.75 -1.5 ]]


In [14]:
# №9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -7 до 7 та транспонуйте її.
import numpy as np

np.random.seed(0)

matrix = np.random.uniform(-7, 7, size=(4, 4))
print("Оригінальна матриця:")
print(matrix)
transposed_matrix = matrix.T
print("Транспонована матриця:")
print(transposed_matrix)


Оригінальна матриця:
[[ 0.68338905  3.01265113  1.43868727  0.62836456]
 [-1.06883281  2.04251758 -0.87377904  5.48482201]
 [ 6.49127865 -1.63181874  4.08415053  0.40452888]
 [ 0.95262386  5.95835294 -6.00549519 -5.7801898 ]]
Транспонована матриця:
[[ 0.68338905 -1.06883281  6.49127865  0.95262386]
 [ 3.01265113  2.04251758 -1.63181874  5.95835294]
 [ 1.43868727 -0.87377904  4.08415053 -6.00549519]
 [ 0.62836456  5.48482201  0.40452888 -5.7801898 ]]


In [15]:
# №10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, 
# а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор
import numpy as np

np.random.seed(0)

matrix = np.random.uniform(0, 1, size=(3, 4))
print("Матриця 3x4:")
print(matrix)

vector = np.random.uniform(0, 1, size=(4, 1))
print("Вектор 4x1:")
print(vector)
product = np.dot(matrix, vector)
print("Добуток матриці на вектор:")
print(product)


Матриця 3x4:
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]
Вектор 4x1:
[[0.56804456]
 [0.92559664]
 [0.07103606]
 [0.0871293 ]]
Добуток матриці на вектор:
[[1.06402062]
 [0.94727625]
 [1.00463884]]


In [16]:
# №11 Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, 
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import numpy as np

np.random.seed(0)

matrix = np.random.uniform(0, 1, size=(2, 3))
print("Матриця 2x3:")
print(matrix)

vector = np.random.randint(1, 11, size=(3, 1))
print("Вектор 3x1:")
print(vector)
product = np.dot(matrix, vector)
print("Добуток матриці на вектор:")
print(product)


Матриця 2x3:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]
Вектор 3x1:
[[5]
 [8]
 [7]]
Добуток матриці на вектор:
[[12.68492608]
 [10.6349131 ]]


In [17]:
# №12 Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та 
# знайдіть відношення елементів другого стовпця другої матриці до відповідних елементів першої матриці (поелементне ділення).
import numpy as np

np.random.seed(0)

matrix1 = np.random.randint(1, 11, size=(9, 9))
matrix2 = np.random.randint(1, 11, size=(9, 9))

print("Перша матриця 9x9:")
print(matrix1)

print("Друга матриця 9x9:")
print(matrix2)
second_column_matrix2 = matrix2[:, 1]


result = second_column_matrix2 / matrix1[:, 1]

print("Відношення елементів другого стовпця другої матриці до відповідних елементів першої матриці:")
print(result)


Перша матриця 9x9:
[[ 6  1  4  4  8 10  4  6  3]
 [ 5  8  7  9  9  2  7  8  8]
 [ 9  2  6 10  9 10  5  4  1]
 [ 4  6  1  3  4  9  2  4  4]
 [ 4  8  1  2 10 10  1  5  8]
 [ 4  3  8  3  1  1  5  6  6]
 [ 7  9  5  2  5 10  9  2  2]
 [ 8 10 10  4  7  8  3  1  4]
 [ 6 10  5  5  7  5  5  4  5]]
Друга матриця 9x9:
[[ 5  9  5  4  8  6  6  1  2]
 [ 6 10  4  1  6  1  2  3  5]
 [ 3  1  4  3  1  8  6 10  1]
 [ 3  8  3 10  3  4  4  3  4]
 [ 5  2  3 10  2  5  7  9  3]
 [ 4  1  1  7  1  7  4  4  9]
 [ 9  9  3  4  3  1  9  9  4]
 [ 9  3  9  5  4  1  5  4  7]
 [10  9  1  9  6 10  1 10  7]]
Відношення елементів другого стовпця другої матриці до відповідних елементів першої матриці:
[9.         1.25       0.5        1.33333333 0.25       0.33333333
 1.         0.3        0.9       ]


In [19]:
# №13 Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток їх елементів.
import numpy as np

np.random.seed(0)

matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))

print("Перша матриця 3x3:")
print(matrix1)

print("Друга матриця 3x3:")
print(matrix2)
product = np.dot(matrix1, matrix2)
print("Добуток матриць:")
print(product)


Перша матриця 3x3:
[[ 6  1  4]
 [ 4  8 10]
 [ 4  6  3]]
Друга матриця 3x3:
[[5 8 7]
 [9 9 2]
 [7 8 8]]
Добуток матриць:
[[ 67  89  76]
 [162 184 124]
 [ 95 110  64]]


In [18]:
# №14 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 5 та знайдіть середнє геометричне значення елементів матриці.
import numpy as np
from scipy.stats import gmean

np.random.seed(0)

matrix = np.random.randint(1, 6, size=(3, 3))
print("Матриця 3x3:")
print(matrix)

elements = matrix.flatten()

geom_mean = gmean(elements)
print("Середнє геометричне значення елементів матриці:")
print(geom_mean)


Матриця 3x3:
[[5 1 4]
 [4 4 2]
 [4 3 5]]
Середнє геометричне значення елементів матриці:
3.2312468423897185


In [31]:
# №15 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, 
# що містить найменше за модулем ціле значення в кожному рядку матриці.
import numpy as np

matrix = np.random.uniform(-2, 2, (3, 3))

sums = np.sum(np.abs(matrix.astype(int)), axis=0)
min_column_index = np.argmin(sums)

result_column = matrix[:, min_column_index]

print("Матриця:")
print(matrix)
print("\nВектор-стовпчик:")
print(result_column.reshape(-1, 1))

Матриця:
[[-0.20320905  1.91428371 -1.53519236]
 [ 1.06809481 -0.35271944  0.70175632]
 [-1.0008149  -0.74712667  1.86166488]]

Вектор-стовпчик:
[[ 1.91428371]
 [-0.35271944]
 [-0.74712667]]


Висновок: Була проведена робота в предметній області лінійної алгебри, з використанням
мови Python, включаючи як базові, так і просунуті методи чисельного аналізу та маніпулювання матрицями, здобуті важливі навички обробки даних та розв'язування математичних задач.